version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby 
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Bundler 
          command: |
            gem install bundler
      - run:
          name: Install Gems
          command: |
            bundle install 
      - run:
          name: Deploy 
          command: |
            apt-get update && apt-get install default-jre
            ./deploy.sh
